version: '3.8'
services:
  optiroute-backend:
    build: .
    ports:
      - "8081:8081"
    environment:
      - JWT_SECRET=thisIsASecretKeyForJwtTokenGenerationWhichMustBeLongEnough
    restart: unless-stopped
